export const API = {
    AUTH: {
        ME: '/api/auth/me',
        LOGIN: '/api/auth/login',
        REGISTER: '/api/auth/register',
        LOGOUT: '/api/auth/logout',
        SESSIONS: '/api/auth/sessions',
        SESSIONS_REVOKE: '/api/auth/sessions/revoke',
        SESSIONS_REVOKE_ALL: '/api/auth/sessions/revoke-all',
        VERIFICATION_CHALLENGE: '/api/auth/verification/challenge',
        VERIFICATION_SUBMIT: '/api/auth/verification/submit',
    },
    USERS: {
        PATCH: (userId: string) => `/api/users/${userId}`,
        KYC_SUBMIT: (userId: string) => `/api/users/${userId}/kyc/submit`,
        WALLET_TOPUP: '/api/wallet/topup',
        WALLET_TOPUPS: '/api/wallet/topups',
    },
    PRODUCTS: {
        LIST: '/api/products',
        SAVED: '/api/products/saved',
        SAVE: (productId: string) => `/api/products/${productId}/save`,
        RECENT_VIEWED: '/api/products/recent/viewed',
        VIEW: (productId: string) => `/api/products/${productId}/view`,
        DETAIL: (productId: string) => `/api/products/${productId}`,
        PUBLIC: (productId: string) => `/api/products/${productId}/public`,
        CREATE: '/api/products',
    },
    TRANSACTIONS: {
        LIST: '/api/transactions',
        CREATE: '/api/transactions',
        CONFIRM: (txnId: string) => `/api/transactions/${txnId}/confirm`,
        DISPUTE: (txnId: string) => `/api/transactions/${txnId}/dispute`,
        DISPUTE_EVIDENCE: (txnId: string) => `/api/transactions/${txnId}/dispute/evidence`,
    },
    ORDERS: {
        LIST: '/api/orders',
        TIMELINE: (orderId: string) => `/api/orders/${orderId}/timeline`,
    },
    REVIEWS: {
        CREATE: '/api/reviews',
        BY_PRODUCT: (productId: string) => `/api/reviews/products/${productId}`,
    },
    CAMPAIGNS: {
        LIST: '/api/campaigns',
        CREATE: '/api/campaigns',
        UPDATE_STATUS: (campaignId: string) => `/api/campaigns/${campaignId}/status`,
    },
    BIDS: {
        CREATE: '/api/bids',
    },
    OFFERS: {
        LIST: '/api/offers',
        CREATE: '/api/offers',
        COUNTER: (offerId: string) => `/api/offers/${offerId}/counter`,
        ACCEPT: (offerId: string) => `/api/offers/${offerId}/accept`,
        REJECT: (offerId: string) => `/api/offers/${offerId}/reject`,
    },
    CHATS: {
        LIST: '/api/chats',
        CREATE: '/api/chats',
        REPLAY: '/api/chats/replay',
        MESSAGES: (chatId: string) => `/api/chats/${chatId}/messages`,
        MESSAGE_READ: (chatId: string, messageId: string) => `/api/chats/${chatId}/messages/${messageId}/read`,
    },
    QUESTS: {
        LIST: '/api/quests',
        COMPLETE: (questId: string) => `/api/quests/${questId}/complete`,
    },
    LEADERBOARD: {
        LIST: '/api/leaderboard',
    },
    NOTIFICATIONS: {
        LIST: '/api/notifications',
        CREATE: '/api/notifications',
        MARK_READ: (notificationId: string) => `/api/notifications/${notificationId}/read`,
    },
    REFERRALS: {
        LIST: '/api/referrals',
        CREATE: '/api/referrals',
        QUALIFY: (referralId: string) => `/api/referrals/${referralId}/qualify`,
    },
    EXTENSION: {
        DETECT: '/api/ai/detect',
        PRICE: '/api/ai/price',
        FRAUD: '/api/fraud',
        RECOMMEND: '/api/ai/recommend',
        NLP_SUGGEST: '/api/nlp/suggest',
    },
    ADMIN: {
        HEATMAP: '/api/admin/heatmap',
        EXPORT: '/api/admin/export',
        EXPORT_JOBS: '/api/admin/export/jobs',
        EXPORT_JOB_DETAIL: (exportJobId: string) => `/api/admin/export/jobs/${exportJobId}`,
        FLAGS: '/api/admin/flags',
        DISPUTES: '/api/admin/disputes',
        RESOLVE_FLAG: (flagId: string) => `/api/admin/flags/${flagId}`,
        DECIDE_DISPUTE: (disputeId: string) => `/api/admin/disputes/${disputeId}/decide`,
        MODERATION_UNDO: (actionId: string) => `/api/admin/moderation/${actionId}/undo`,
        AUDIT_LOGS: '/api/admin/audit/logs',
        AUDIT_RETENTION_RUN: '/api/admin/audit/retention/run',
        USERS: '/api/admin/users',
        USER_DETAIL: (userId: string) => `/api/admin/users/${userId}`,
    },
    SELLER: {
        ANALYTICS_LISTINGS: '/api/seller/analytics/listings',
        BULK_IMPORT: '/api/seller/bulk-import',
        PAYOUT_LEDGER: '/api/seller/payouts/ledger',
    },
    RISK: {
        SCORE_USER: (userId: string) => `/api/risk/score/users/${userId}`,
    },
}