import { GENERATED_REALTIME_EVENTS } from "./generated-events";

export const REALTIME_EVENTS = {
	CHAT_MESSAGE_CREATED_V1: GENERATED_REALTIME_EVENTS.CHAT_MESSAGE_CREATED_V1,
	CHAT_AI_SUGGESTION_CREATED_V1: GENERATED_REALTIME_EVENTS.CHAT_SUGGESTION_CREATED_V1,
	CHAT_MESSAGE_RECEIPT_UPDATED_V1: GENERATED_REALTIME_EVENTS.CHAT_MESSAGE_RECEIPT_UPDATED_V1,
	AUCTION_BID_PLACED_V1: GENERATED_REALTIME_EVENTS.AUCTION_BID_PLACED_V1,
	ADMIN_FLAG_UPDATED_V1: GENERATED_REALTIME_EVENTS.ADMIN_FLAG_UPDATED_V1,
	ADMIN_DISPUTE_DECIDED_V1: GENERATED_REALTIME_EVENTS.ADMIN_DISPUTE_DECIDED_V1,
	CHAT_MESSAGE_LEGACY: GENERATED_REALTIME_EVENTS.CHAT_MESSAGE,
	CHAT_RECEIPT_LEGACY: GENERATED_REALTIME_EVENTS.CHAT_RECEIPT,
	AUCTION_BID_LEGACY: GENERATED_REALTIME_EVENTS.AUCTION_BID,
} as const;
