// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-realtime-models.mjs from shared-event-schema/socket-events.schema.json

export const GENERATED_REALTIME_EVENTS = {
  CHAT_MESSAGE_CREATED_V1: "chat:message.created.v1",
  CHAT_SUGGESTION_CREATED_V1: "chat:suggestion.created.v1",
  CHAT_MESSAGE_RECEIPT_UPDATED_V1: "chat:message.receipt.updated.v1",
  AUCTION_BID_PLACED_V1: "auction:bid.placed.v1",
  ADMIN_FLAG_UPDATED_V1: "admin:flag.updated.v1",
  ADMIN_DISPUTE_DECIDED_V1: "admin:dispute.decided.v1",
  CHAT_MESSAGE: "chat:message",
  CHAT_RECEIPT: "chat:receipt",
  AUCTION_BID: "auction:bid",
} as const;

export type ChatMessageCreatedV1Payload = { "messageId": string; "chatId": string; "senderId": string; "content": string; "timestamp": string | Record<string, unknown> | null; "isAISuggestion": boolean; "deliveredTo": string[]; "readBy": string[] };
export type ChatSuggestionCreatedV1Payload = { "messageId": string; "chatId": string; "senderId": string; "content": string; "timestamp": string | Record<string, unknown> | null; "isAISuggestion": boolean; "deliveredTo": string[]; "readBy": string[] };
export type ChatMessageReceiptUpdatedV1Payload = { "chatId": string; "messageId": string; "deliveredTo": string[]; "readBy": string[]; "updatedAt": string };
export type AuctionBidPlacedV1Payload = { "productId": string; "bid": { "bidId": string; "productId": string; "bidderId": string; "amount": number; "timestamp": string | Record<string, unknown> | null } };
export type AdminFlagUpdatedV1Payload = { "flagId": string; "sellerId": string; "resolved": boolean; "reason": string; "actionBy": string; "updatedAt": string };
export type AdminDisputeDecidedV1Payload = { "disputeId": string; "transactionId": string; "orderId"?: string | null; "buyerId": string; "sellerId": string; "outcome": string; "transactionStatus": string; "orderStatus": string; "updatedAt": string };

export type GeneratedRealtimeEventName =
  | "chat:message.created.v1"
  | "chat:suggestion.created.v1"
  | "chat:message.receipt.updated.v1"
  | "auction:bid.placed.v1"
  | "admin:flag.updated.v1"
  | "admin:dispute.decided.v1"
  | "chat:message"
  | "chat:receipt"
  | "auction:bid"
;

export type GeneratedRealtimePayloadByEvent = {
  "chat:message.created.v1": ChatMessageCreatedV1Payload;
  "chat:suggestion.created.v1": ChatSuggestionCreatedV1Payload;
  "chat:message.receipt.updated.v1": ChatMessageReceiptUpdatedV1Payload;
  "auction:bid.placed.v1": AuctionBidPlacedV1Payload;
  "admin:flag.updated.v1": AdminFlagUpdatedV1Payload;
  "admin:dispute.decided.v1": AdminDisputeDecidedV1Payload;
  "chat:message": GeneratedRealtimePayloadByEvent["chat:message.created.v1"];
  "chat:receipt": GeneratedRealtimePayloadByEvent["chat:message.receipt.updated.v1"];
  "auction:bid": GeneratedRealtimePayloadByEvent["auction:bid.placed.v1"];
};

export type GeneratedRealtimeEventEnvelope<T extends GeneratedRealtimeEventName = GeneratedRealtimeEventName> = {
  type: T;
  payload: GeneratedRealtimePayloadByEvent[T];
};

